name: Vite Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Configure Git identity
        run: |
          git config user.email "actions@example.com"
          git config user.name "GitHub Actions"
        if: success() # Only configure Git identity if the build was successful

      - name: Create a tag with a fixed version
        run: git tag -a v1.0 -m "Release v1.0"
        if: success() # Only create a tag if the build was successful

      - name: Push the tag to the repository
        run: git push origin v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_PAT }}
        if: success() # Only push the tag if it was created

      - name: Create a release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/* # Upload all files in the build directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
