name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Vite project
        run: npm run build

      - name: Create Tag
        run: git tag v1.0.0
        if: success()

      - name: Push Tag
        run: git push origin v1.0.0
        if: success()

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip # Include the zip file
          tag_name: v1.0.0 # Replace with the same version as above
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_PAT }}

      - name: Zip dist directory
        run: |
          zip -r dist.zip dist

      - name: Upload zip to release
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip

      - name: Get Release URL
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.html_url }}"
