name: Deploy to FTP

on:
  # Trigger the workflow when the other workflow completes successfully.
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  deploy-to-ftp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dawidd6/action-download-artifact@v2
        name: Download build code
        with:
          name: build-artifacts
          workflow: Build

      - run: ls

      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        name: Deploy to FTP
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: test
          dry-run: true